### ISSUE TITLE
Recent update to svgo to 5.2.1 breaks builds.

### ISSUE THREAD

**Issue by obble80** [imagemin/imagemin-svgo#25]
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: this is not a typed array.
    at Function.from (native)
    at /redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/index.js:25:19
    at optimizeOnceCallback (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo.js:44:17)
    at /redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo.js:65:9
    at Object.sax.onend (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/svg2js.js:156:13)
    at emit (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:640:35)
    at end (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:683:5)
    at Object.write (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:991:14)
    at Object.SAXParser.close (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:157:38)
    at module.exports (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/svg2js.js:169:28)

**Comment by bgha-stibosystems** [comment]
Yes, this is the case for builds running older node versions than 6, from what I can find.

`Buffer.from` was introduced in node 6, whereas `new Buffer(...)` works on all versions of node

**Comment by twjacobsen** [comment]
Yes, this is the case for builds running older node versions than 6, from what I can find.

`Buffer.from` was introduced in node 6, whereas `new Buffer(...)` works on all versions of node

**Comment by themattconnolly** [comment]
I'm running into the same issue with node 6.10.1. I can't tell if the problem is with the actual SVG files being passed in, but it worked fine in version 5.2.0.

**Comment by Zephir77167** [comment]
I'm stuck on this too, using image-webpack-loader which has a dependency on svgo, but I can't upgrade node to 6...

**Comment by calebfaruki** [comment]
I'm having the same error. I invoke the gulp-imagemin in the following way:

````
function images() {
  return gulp.src('app/client_assets/images/**/*.*', {base: 'app'})
    .pipe($.plumber({errorHandler: common.catchError}))
    .pipe($.imagemin())
    .pipe(gulp.dest("./public"));
}
````

Environment:
npm: 4.4.4
node: 5.6.0
gulp: 3.9.1
gulp-imagemin: 3.2.0
imagemin: 5.2.2
imagemin-svgo: 5.2.1
sax: 1.2.2

````
{ [TypeError: this is not a typed array.]
  name: 'TypeError',
  message: 'this is not a typed array.',
  stack: 'TypeError: this is not a typed array.
      at Function.from (native)
      at --------/node_modules/imagemin-svgo/index.js:25:19
      at optimizeOnceCallback (--------/node_modules/svgo/lib/svgo.js:44:17)
      at --------/node_modules/svgo/lib/svgo.js:65:9
      at Object.sax.onend (--------/node_modules/svgo/lib/svgo/svg2js.js:156:13)
      at emit (--------/node_modules/sax/lib/sax.js:640:35)
      at end (--------/node_modules/sax/lib/sax.js:683:5)
      at Object.write (--------/node_modules/sax/lib/sax.js:991:14)
      at Object.SAXParser.close (--------/node_modules/sax/lib/sax.js:157:38)
      at module.exports (--------/node_modules/svgo/lib/svgo/svg2js.js:169:28)
      at [object Object].SVGO._optimizeOnce (--------/node_modules/svgo/lib/svgo.js:56:5)
      at optimizeOnceCallback (--------/node_modules/svgo/lib/svgo.js:42:23)
      at --------/node_modules/svgo/lib/svgo.js:65:9
      at Object.sax.onend (--------/node_modules/svgo/lib/svgo/svg2js.js:156:13)
      at emit (--------/node_modules/sax/lib/sax.js:640:35)
      at end (--------/node_modules/sax/lib/sax.js:683:5)
      at Object.write (--------/node_modules/sax/lib/sax.js:991:14)
      at Object.SAXParser.close (--------/node_modules/sax/lib/sax.js:157:38)
      at module.exports (--------/node_modules/svgo/lib/svgo/svg2js.js:169:28)
      at [object Object].SVGO._optimizeOnce (--------/node_modules/svgo/lib/svgo.js:56:5)
      at [object Object].SVGO.optimize (--------/node_modules/svgo/lib/svgo.js:49:11)
      at --------/node_modules/imagemin-svgo/index.js:19:8
      at --------/node_modules/imagemin-svgo/index.js:18:9
      at --------/node_modules/promise.pipe/index.js:25:18
      at process._tickCallback (node.js:402:9),
  fileName: '--------/app/client_assets/images/non-funnel/testimonials/unpacking.svg',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-imagemin' }
````

After updating my node installation to the latest stable release, imagemin ran with no errors. In my case, I upgraded to node 7.8.0.

Source: https://davidwalsh.name/upgrade-nodejs
````
$ sudo npm cache clean -f
$ sudo npm install -g n
$ sudo n stable
$ node -v
````

**Comment by jarnaiz** [comment]
Same error here.
You can see the details in travis: https://travis-ci.org/Upplication/landing/builds/216681802

Plz fix it, node 4 is LTS active right now.

**Comment by kieranmv95** [comment]
This is still happening for me anyone know of a solution?

**Comment by nijikokun** [comment]
A **breaking change** in a **patch** is not a good sign.

**Comment by tombh** [comment]
This just suddenly turned up on our Travis builds. Don't know why it hadn't before, maybe something I did though.

**Comment by strarsis** [comment]
I have a similar issue suddenly, though in this case node simply exits without any indication of error 😱 .

For reproducing the issue I extracted the relevant code from current imagemin-svgo:

Use node v6.x (current LTS) and install svgo module, it also happened with v4.x btw.:
````
$ nvm install v6
$ nvm use v6

$ npm install svgo
````
```js
'use strict';

const SVGO = require('svgo');

var buf = '<svg></svg>';
var opts = {
  multipass: true
};

const svgo = new SVGO(opts);

new Promise(function(resolve, reject) {
        console.log('Before optimize');
        svgo.optimize(buf, function(res) {
        console.log('After optimize');

                if (res.error) {
                        reject(new Error(res.error));
                        return;
                }

                resolve(Buffer.from(res.data));
        })
})
.then(function(e) {
        console.log('After Resolve: ' + e);
});
````

Run the test script:
````
$ node test.js
Before optimize
````

That's all, the whole thing seems to crash with svgo.optimize(...).
